### ISSUE TITLE
The config value for :parent-key key cannot be "parent.config.filename"

### ISSUE THREAD

**Issue by nxvipin** [kumarshantanu/keypin#4]
Example invocation: 

```
(k/read-config [(:config-file options)]
                               {:parent-key "parent.config.filename"})
```

Error:

```
[keypin] [error] Error realizing template '${discovered.app.version}', no value found for property 'discovered.app.version'
Exception in thread "main" java.lang.IllegalArgumentException: Error realizing template '${discovered.app.version}', no value found for property 'discovered.app.version', compiling:(/private/var/folders/wp/jl8csrw96bx0nnbs49yj3ggdkt6d1l/T/form-init7538858116212829087.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Error realizing template '${discovered.app.version}', no value found for property 'discovered.app.version'
	at keypin.Config.exit(Config.java:287)
	at keypin.Config.readValue(Config.java:272)
	at keypin.Config.realize(Config.java:216)
	at keypin.Config.realize(Config.java:164)
	at keypin.Config.realize(Config.java:132)
	at keypin.core$realize_config.invokeStatic(core.clj:106)
	at keypin.core$realize_config.invoke(core.clj:94)
	at keypin.core$read_config.invokeStatic(core.clj:126)
	at keypin.core$read_config.invoke(core.clj:109)
	at com.concur.service.profile.common.tools.dbmigration$_main.invokeStatic(dbmigration.clj:96)
	at com.concur.service.profile.common.tools.dbmigration$_main.doInvoke(dbmigration.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at clojure.lang.Var.invoke(Var.java:430)
	at user$eval11.invokeStatic(form-init7538858116212829087.clj:1)
	at user$eval11.invoke(form-init7538858116212829087.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

This works fine if I change the value to something else (and updating the config files accordingly):

```
(k/read-config [(:config-file options)]
                               {:parent-key "parent-config-filename"})
```

**Comment by kumarshantanu** [comment]
This issue is due to an unresolvable variable in the config file. Not a Keypin issue.
